-- MySQL Script generated by MySQL Workbench
-- Wed Nov 19 13:04:17 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Schema pohome
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pohome
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pohome` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `pohome` ;

-- -----------------------------------------------------
-- Table `pohome`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`users` ;

CREATE TABLE IF NOT EXISTS `pohome`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(15) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `email` VARCHAR(25) NOT NULL,
  `mobile` CHAR(11) NULL,
  `realname` VARCHAR(8) NULL,
  `identity_card_num` VARCHAR(18) NULL,
  `birthday` DATE NULL,
  `gender` ENUM('M','F') NULL,
  `province` TINYINT NULL,
  `city` TINYINT NULL,
  `qq` VARCHAR(15) NULL,
  `weibo` VARCHAR(30) NULL,
  `taobao_id` VARCHAR(25) NULL,
  `weixin_id` VARCHAR(20) NULL,
  `referee_id` INT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `last_visit_at` DATETIME NOT NULL,
  `last_visit_ip` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `mobile_UNIQUE` (`mobile` ASC),
  INDEX `fk_users_users_idx` (`referee_id` ASC),
  UNIQUE INDEX `taobao_id_UNIQUE` (`taobao_id` ASC),
  CONSTRAINT `fk_users_users`
    FOREIGN KEY (`referee_id`)
    REFERENCES `pohome`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`pets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`pets` ;

CREATE TABLE IF NOT EXISTS `pohome`.`pets` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  `avatar` INT UNSIGNED NOT NULL DEFAULT 0,
  `species` ENUM('D','C') NOT NULL,
  `gender` ENUM('M','F') NOT NULL,
  `breed` VARCHAR(10) NOT NULL,
  `birthday` DATE NOT NULL,
  `body_size` ENUM('XL','L','M','S') NOT NULL,
  `character` VARCHAR(80) NOT NULL,
  `health` VARCHAR(80) NOT NULL,
  `neutered` TINYINT(1) NOT NULL,
  `adoption_notice` VARCHAR(400) NULL,
  `adoptable` TINYINT(1) NOT NULL,
  `draft` TINYINT(1) NOT NULL,
  `viewed` INT UNSIGNED NOT NULL,
  `favorite` INT UNSIGNED NOT NULL,
  `creator_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `NAME` (`name` ASC),
  INDEX `fk_pets_users1_idx` (`creator_id` ASC),
  CONSTRAINT `fk_pets_users1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `pohome`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`pohome_pet_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`pohome_pet_info` ;

CREATE TABLE IF NOT EXISTS `pohome`.`pohome_pet_info` (
  `pet_id` INT UNSIGNED NOT NULL,
  `angel_id` SMALLINT UNSIGNED NULL,
  `entry_date` DATE NOT NULL,
  `location` TINYINT UNSIGNED NULL,
  `status` TINYINT UNSIGNED NULL,
  `neuter_date` DATE NULL,
  `next_immune_date` DATE NULL,
  `next_anthelmintic_date` DATE NULL,
  INDEX `fk_pohome_pet_info_pets1_idx` (`pet_id` ASC),
  UNIQUE INDEX `angel_id_UNIQUE` (`angel_id` ASC),
  UNIQUE INDEX `pet_id_UNIQUE` (`pet_id` ASC),
  CONSTRAINT `fk_pohome_pet_info_pets1`
    FOREIGN KEY (`pet_id`)
    REFERENCES `pohome`.`pets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`blogs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`blogs` ;

CREATE TABLE IF NOT EXISTS `pohome`.`blogs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(20) NOT NULL,
  `featured_image` VARCHAR(45) NULL,
  `content` TEXT NOT NULL,
  `catelog_id` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `author_id` INT UNSIGNED NOT NULL,
  `draft` TINYINT(1) NOT NULL,
  `viewed` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_blogs_users1_idx` (`author_id` ASC),
  CONSTRAINT `fk_blogs_users1`
    FOREIGN KEY (`author_id`)
    REFERENCES `pohome`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`public_pet_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`public_pet_info` ;

CREATE TABLE IF NOT EXISTS `pohome`.`public_pet_info` (
  `pet_id` INT UNSIGNED NOT NULL,
  `type` ENUM('R','S') NOT NULL,
  `hope` VARCHAR(20) NOT NULL,
  `story` TEXT NOT NULL,
  `location_limit` ENUM('P','C','N') NOT NULL,
  INDEX `fk_public_pet_info_pets1_idx` (`pet_id` ASC),
  CONSTRAINT `fk_public_pet_info_pets1`
    FOREIGN KEY (`pet_id`)
    REFERENCES `pohome`.`pets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`events` ;

CREATE TABLE IF NOT EXISTS `pohome`.`events` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(20) NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NULL,
  `location` VARCHAR(20) NOT NULL DEFAULT '',
  `content` TEXT NOT NULL,
  `deadline` DATETIME NULL,
  `member_limit` TINYINT NOT NULL,
  `type` TINYINT NULL,
  `author_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `taobao_link` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  INDEX `fk_event_users1_idx` (`author_id` ASC),
  CONSTRAINT `fk_event_users1`
    FOREIGN KEY (`author_id`)
    REFERENCES `pohome`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`files` ;

CREATE TABLE IF NOT EXISTS `pohome`.`files` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `filename` CHAR(19) NOT NULL,
  `uploader_id` INT UNSIGNED NOT NULL,
  `upload_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
