-- MySQL Script generated by MySQL Workbench
-- Wed Jan 14 13:48:52 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pohome
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pohome
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pohome` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `pohome` ;

-- -----------------------------------------------------
-- Table `pohome`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`user` (
  `id` CHAR(13) NOT NULL,
  `username` VARCHAR(15) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `email` VARCHAR(25) NOT NULL,
  `mobile` CHAR(11) NULL,
  `created_at` DATETIME NOT NULL,
  `last_visit_at` DATETIME NOT NULL,
  `last_visit_ip` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `mobile_UNIQUE` (`mobile` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`roles` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`permissions` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`user_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`user_has_roles` (
  `user_id` CHAR(13) NOT NULL,
  `role_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_users_has_roles_roles1_idx` (`role_id` ASC),
  INDEX `fk_users_has_roles_users1_idx` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`role_has_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`role_has_permissions` (
  `role_id` SMALLINT UNSIGNED NOT NULL,
  `permission_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`role_id`, `permission_id`),
  INDEX `fk_roles_has_permissions_permissions1_idx` (`permission_id` ASC),
  INDEX `fk_roles_has_permissions_roles1_idx` (`role_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`province` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`pet` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  `species` ENUM('D','C') NOT NULL,
  `gender` ENUM('M','F') NOT NULL,
  `breed` VARCHAR(10) NOT NULL,
  `birthday` DATE NOT NULL,
  `body_size` ENUM('L','M','S') NOT NULL,
  `avatar` CHAR(21) NOT NULL,
  `neutered` TINYINT(1) NOT NULL,
  `location` TINYINT UNSIGNED NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL,
  `adoptable` TINYINT(1) NOT NULL,
  `draft` TINYINT(1) NOT NULL,
  `viewed` INT UNSIGNED NOT NULL,
  `favorite` INT UNSIGNED NOT NULL,
  `creator_id` CHAR(13) NOT NULL,
  `created_at` DATETIME NOT NULL COMMENT '	',
  `modified_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `pet_name_INDEX` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`pet_extra_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`pet_extra_info` (
  `pet_id` INT UNSIGNED NOT NULL,
  `character` VARCHAR(40) NOT NULL,
  `health` VARCHAR(40) NOT NULL,
  `notice` VARCHAR(400) NULL,
  `entry_date` DATE NOT NULL,
  `neuter_date` DATE NULL,
  `last_immune_date` DATE NULL,
  `last_kill_insect_date` DATE NULL,
  `last_bath_date` DATE NULL,
  `angel_id` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  INDEX `fk_pet_extra_info_pet1_idx` (`pet_id` ASC),
  UNIQUE INDEX `angel_id_UNIQUE` (`angel_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`user_extra_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`user_extra_info` (
  `user_id` CHAR(13) NOT NULL,
  `realname` VARCHAR(15) NULL,
  `id_num` CHAR(18) NULL,
  `birthday` DATE NULL,
  `gender` ENUM('M','F') NULL,
  `province` TINYINT UNSIGNED NULL,
  `city` TINYINT UNSIGNED NULL,
  `qq` VARCHAR(15) NULL,
  `weibo` VARCHAR(30) NULL,
  `taobao` VARCHAR(25) NULL,
  `referee_id` INT UNSIGNED NULL,
  INDEX `fk_user_extra_info_user1_idx` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`log` (
  `id` INT UNSIGNED NOT NULL,
  `type` TINYINT UNSIGNED NOT NULL,
  `sub_type` TINYINT UNSIGNED NOT NULL,
  `datetime` DATETIME NOT NULL,
  `creator_id` CHAR(13) NOT NULL,
  `content` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`contribution_intension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`contribution_intension` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `intension` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`service_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`service_record` (
  `id` CHAR(13) NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `contribution_hour` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_volunteer_service_record_user1_idx` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`volunteer_contribution_intension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`volunteer_contribution_intension` (
  `id` INT UNSIGNED NOT NULL,
  `user_id` CHAR(13) NOT NULL,
  `contribution_intension_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_volunteer_contribution_intension_user1_idx` (`user_id` ASC),
  INDEX `fk_volunteer_contribution_intension_contribution_intension1_idx` (`contribution_intension_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`event` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(20) NOT NULL,
  `begin` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `deadline` DATETIME NULL,
  `location` VARCHAR(20) NOT NULL,
  `content` TEXT NOT NULL,
  `member_limit` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `type_id` TINYINT UNSIGNED NOT NULL,
  `publisher_id` CHAR(13) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`blog` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(20) NOT NULL,
  `content` TEXT NOT NULL,
  `abstract` VARCHAR(250) NOT NULL,
  `feature_image` CHAR(21) NOT NULL,
  `catelog_id` TINYINT UNSIGNED NOT NULL,
  `author_id` CHAR(13) NOT NULL,
  `draft` TINYINT(1) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `published_at` DATETIME NOT NULL,
  `viewed` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`event_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`event_type` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`blog_catelog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`blog_catelog` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`city` (
  `id` SMALLINT NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`event_application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`event_application` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_id` INT UNSIGNED NOT NULL,
  `applicant_id` CHAR(13) NOT NULL,
  `number_of_people` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `location` VARCHAR(20) NOT NULL,
  `has_car` TINYINT(1) NOT NULL,
  `addition_remark` VARCHAR(100) NOT NULL,
  `applied_at` DATETIME NOT NULL,
  `contacted` TINYINT(1) NOT NULL DEFAULT 0,
  `approved` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`adoption_application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`adoption_application` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pet_id` INT UNSIGNED NOT NULL,
  `applicant_id` CHAR(13) NOT NULL,
  `application_form` TEXT NOT NULL,
  `applied_at` DATETIME NOT NULL,
  `status` ENUM('S','R','EC','PC','V','A','D') NOT NULL,
  `closed` TINYINT(1) NOT NULL DEFAULT 0,
  `closed_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`contact_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`contact_record` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `application_id` CHAR(13) NOT NULL,
  `contact_person_id` CHAR(13) NOT NULL,
  `type` ENUM('P','E','R') NOT NULL,
  `opinion` VARCHAR(400) NOT NULL,
  `datetime` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`pet_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`pet_log` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pet_id` INT UNSIGNED NOT NULL,
  `log_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`file` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `filename` CHAR(21) NOT NULL,
  `path` VARCHAR(100) NOT NULL,
  `size` INT UNSIGNED NOT NULL,
  `uploader_id` CHAR(13) NOT NULL,
  `upload_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`pet_photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`pet_photo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pet_id` INT UNSIGNED NOT NULL,
  `filename` CHAR(21) NOT NULL,
  `priority` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`pet_story`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pohome`.`pet_story` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pet_id` INT UNSIGNED NOT NULL,
  `blog_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
