-- MySQL Script generated by MySQL Workbench
-- Fri Jan 16 13:48:00 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pohome
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pohome` ;

-- -----------------------------------------------------
-- Schema pohome
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pohome` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `pohome` ;

-- -----------------------------------------------------
-- Table `pohome`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`user` ;

CREATE TABLE IF NOT EXISTS `pohome`.`user` (
  `id` CHAR(13) NOT NULL,
  `username` VARCHAR(15) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `email` VARCHAR(25) NOT NULL,
  `mobile` CHAR(11) NULL,
  `created_at` DATETIME NOT NULL,
  `last_visit_at` DATETIME NOT NULL,
  `last_visit_ip` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `mobile_UNIQUE` (`mobile` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`roles` ;

CREATE TABLE IF NOT EXISTS `pohome`.`roles` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`permissions` ;

CREATE TABLE IF NOT EXISTS `pohome`.`permissions` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`user_has_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`user_has_roles` ;

CREATE TABLE IF NOT EXISTS `pohome`.`user_has_roles` (
  `user_id` CHAR(13) NOT NULL,
  `role_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_users_has_roles_roles1_idx` (`role_id` ASC),
  INDEX `fk_users_has_roles_users1_idx` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`role_has_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`role_has_permissions` ;

CREATE TABLE IF NOT EXISTS `pohome`.`role_has_permissions` (
  `role_id` SMALLINT UNSIGNED NOT NULL,
  `permission_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`role_id`, `permission_id`),
  INDEX `fk_roles_has_permissions_permissions1_idx` (`permission_id` ASC),
  INDEX `fk_roles_has_permissions_roles1_idx` (`role_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`province`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`province` ;

CREATE TABLE IF NOT EXISTS `pohome`.`province` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`pet` ;

CREATE TABLE IF NOT EXISTS `pohome`.`pet` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  `species` ENUM('D','C') NOT NULL,
  `gender` ENUM('M','F') NOT NULL,
  `breed` VARCHAR(10) NOT NULL,
  `birthday` DATE NOT NULL,
  `body_size` ENUM('L','M','S') NOT NULL,
  `avatar` CHAR(21) NOT NULL,
  `neutered` TINYINT(1) NOT NULL,
  `location` TINYINT UNSIGNED NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL,
  `adoptable` TINYINT(1) NOT NULL,
  `draft` TINYINT(1) NOT NULL,
  `viewed` INT UNSIGNED NOT NULL,
  `favorite` INT UNSIGNED NOT NULL,
  `creator_id` CHAR(13) NOT NULL,
  `created_at` DATETIME NOT NULL COMMENT '	',
  `modified_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `pet_name_INDEX` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`pet_extra_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`pet_extra_info` ;

CREATE TABLE IF NOT EXISTS `pohome`.`pet_extra_info` (
  `pet_id` INT UNSIGNED NOT NULL,
  `character` VARCHAR(40) NOT NULL,
  `health` VARCHAR(40) NOT NULL,
  `notice` VARCHAR(400) NULL,
  `entry_date` DATE NOT NULL,
  `neuter_date` DATE NULL,
  `last_immune_date` DATE NULL,
  `last_kill_insect_date` DATE NULL,
  `last_bath_date` DATE NULL,
  `angel_id` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  INDEX `fk_pet_extra_info_pet1_idx` (`pet_id` ASC),
  UNIQUE INDEX `angel_id_UNIQUE` (`angel_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`user_extra_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`user_extra_info` ;

CREATE TABLE IF NOT EXISTS `pohome`.`user_extra_info` (
  `user_id` CHAR(13) NOT NULL,
  `realname` VARCHAR(15) NULL,
  `id_num` CHAR(18) NULL,
  `birthday` DATE NULL,
  `gender` ENUM('M','F') NULL,
  `province` TINYINT UNSIGNED NULL,
  `city` TINYINT UNSIGNED NULL,
  `qq` VARCHAR(15) NULL,
  `weibo` VARCHAR(30) NULL,
  `taobao` VARCHAR(25) NULL,
  `referee_id` INT UNSIGNED NULL,
  INDEX `fk_user_extra_info_user1_idx` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`log` ;

CREATE TABLE IF NOT EXISTS `pohome`.`log` (
  `id` INT UNSIGNED NOT NULL,
  `type` TINYINT UNSIGNED NOT NULL,
  `sub_type` TINYINT UNSIGNED NOT NULL,
  `datetime` DATETIME NOT NULL,
  `creator_id` CHAR(13) NOT NULL,
  `content` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`contribution_intension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`contribution_intension` ;

CREATE TABLE IF NOT EXISTS `pohome`.`contribution_intension` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `intension` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`service_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`service_record` ;

CREATE TABLE IF NOT EXISTS `pohome`.`service_record` (
  `id` CHAR(13) NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `contribution_hour` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_volunteer_service_record_user1_idx` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`volunteer_contribution_intension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`volunteer_contribution_intension` ;

CREATE TABLE IF NOT EXISTS `pohome`.`volunteer_contribution_intension` (
  `id` INT UNSIGNED NOT NULL,
  `user_id` CHAR(13) NOT NULL,
  `contribution_intension_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_volunteer_contribution_intension_user1_idx` (`user_id` ASC),
  INDEX `fk_volunteer_contribution_intension_contribution_intension1_idx` (`contribution_intension_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`event` ;

CREATE TABLE IF NOT EXISTS `pohome`.`event` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(20) NOT NULL,
  `begin` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `deadline` DATETIME NULL,
  `location` VARCHAR(20) NOT NULL,
  `content` TEXT NOT NULL,
  `member_limit` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `type_id` TINYINT UNSIGNED NOT NULL,
  `publisher_id` CHAR(13) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`catelog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`catelog` ;

CREATE TABLE IF NOT EXISTS `pohome`.`catelog` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`blog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`blog` ;

CREATE TABLE IF NOT EXISTS `pohome`.`blog` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(20) NOT NULL,
  `content` TEXT NOT NULL,
  `abstract` VARCHAR(250) NOT NULL,
  `feature_image` CHAR(21) NOT NULL,
  `catelog_id` TINYINT UNSIGNED NOT NULL,
  `author_id` CHAR(13) NOT NULL,
  `draft` TINYINT(1) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `published_at` DATETIME NOT NULL,
  `viewed` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_blog_catelog_idx` (`catelog_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`event_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`event_type` ;

CREATE TABLE IF NOT EXISTS `pohome`.`event_type` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`city` ;

CREATE TABLE IF NOT EXISTS `pohome`.`city` (
  `id` SMALLINT NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`event_application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`event_application` ;

CREATE TABLE IF NOT EXISTS `pohome`.`event_application` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_id` INT UNSIGNED NOT NULL,
  `applicant_id` CHAR(13) NOT NULL,
  `number_of_people` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `location` VARCHAR(20) NOT NULL,
  `has_car` TINYINT(1) NOT NULL,
  `addition_remark` VARCHAR(100) NOT NULL,
  `applied_at` DATETIME NOT NULL,
  `contacted` TINYINT(1) NOT NULL DEFAULT 0,
  `approved` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`adoption_application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`adoption_application` ;

CREATE TABLE IF NOT EXISTS `pohome`.`adoption_application` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pet_id` INT UNSIGNED NOT NULL,
  `applicant_id` CHAR(13) NOT NULL,
  `application_form` TEXT NOT NULL,
  `applied_at` DATETIME NOT NULL,
  `status` ENUM('S','R','EC','PC','V','A','D') NOT NULL,
  `closed` TINYINT(1) NOT NULL DEFAULT 0,
  `closed_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`contact_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`contact_record` ;

CREATE TABLE IF NOT EXISTS `pohome`.`contact_record` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `application_id` CHAR(13) NOT NULL,
  `contact_person_id` CHAR(13) NOT NULL,
  `type` ENUM('P','E','R') NOT NULL,
  `opinion` VARCHAR(400) NOT NULL,
  `datetime` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`pet_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`pet_log` ;

CREATE TABLE IF NOT EXISTS `pohome`.`pet_log` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pet_id` INT UNSIGNED NOT NULL,
  `log_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`file` ;

CREATE TABLE IF NOT EXISTS `pohome`.`file` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `filename` CHAR(21) NOT NULL,
  `path` VARCHAR(100) NOT NULL,
  `size` INT UNSIGNED NOT NULL,
  `uploader_id` CHAR(13) NOT NULL,
  `upload_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`pet_photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`pet_photo` ;

CREATE TABLE IF NOT EXISTS `pohome`.`pet_photo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pet_id` INT UNSIGNED NOT NULL,
  `filename` CHAR(21) NOT NULL,
  `priority` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`pet_story`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`pet_story` ;

CREATE TABLE IF NOT EXISTS `pohome`.`pet_story` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pet_id` INT UNSIGNED NOT NULL,
  `blog_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`tag` ;

CREATE TABLE IF NOT EXISTS `pohome`.`tag` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pohome`.`blog_with_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pohome`.`blog_with_tag` ;

CREATE TABLE IF NOT EXISTS `pohome`.`blog_with_tag` (
  `blog_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tag_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`blog_id`),
  INDEX `fk_tag_id_idx` (`tag_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pohome`.`province`
-- -----------------------------------------------------
START TRANSACTION;
USE `pohome`;
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (110000, '北京市');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (120000, '天津市');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (130000, '河北省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (140000, '山西省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (150000, '内蒙古自治区');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (210000, '辽宁省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (220000, '吉林省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (230000, '黑龙江省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (310000, '上海市');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (320000, '江苏省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (330000, '浙江省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (340000, '安徽省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (350000, '福建省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (360000, '江西省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (370000, '山东省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (410000, '河南省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (420000, '湖北省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (430000, '湖南省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (440000, '广东省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (450000, '广西壮族自治区');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (460000, '海南省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (500000, '重庆市');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (510000, '四川省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (520000, '贵州省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (530000, '云南省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (540000, '西藏自治区');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (610000, '陕西省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (620000, '甘肃省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (630000, '青海省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (640000, '宁夏回族自治区');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (650000, '新疆维吾尔自治区');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (710000, '台湾省');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (810000, '香港特别行政区');
INSERT INTO `pohome`.`province` (`id`, `name`) VALUES (820000, '澳门特别行政区');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pohome`.`contribution_intension`
-- -----------------------------------------------------
START TRANSACTION;
USE `pohome`;
INSERT INTO `pohome`.`contribution_intension` (`id`, `intension`) VALUES (NULL, '良乡基地义工服务');
INSERT INTO `pohome`.`contribution_intension` (`id`, `intension`) VALUES (NULL, '模拟家庭义工服务');
INSERT INTO `pohome`.`contribution_intension` (`id`, `intension`) VALUES (NULL, '印刷品平面设计');
INSERT INTO `pohome`.`contribution_intension` (`id`, `intension`) VALUES (NULL, '网站设计');
INSERT INTO `pohome`.`contribution_intension` (`id`, `intension`) VALUES (NULL, '摄影');
INSERT INTO `pohome`.`contribution_intension` (`id`, `intension`) VALUES (NULL, '摄像');
INSERT INTO `pohome`.`contribution_intension` (`id`, `intension`) VALUES (NULL, '文案编辑');
INSERT INTO `pohome`.`contribution_intension` (`id`, `intension`) VALUES (NULL, '产品设计');
INSERT INTO `pohome`.`contribution_intension` (`id`, `intension`) VALUES (NULL, '临时寄养');
INSERT INTO `pohome`.`contribution_intension` (`id`, `intension`) VALUES (NULL, '建筑规划');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pohome`.`catelog`
-- -----------------------------------------------------
START TRANSACTION;
USE `pohome`;
INSERT INTO `pohome`.`catelog` (`id`, `name`) VALUES (NULL, '未分类');
INSERT INTO `pohome`.`catelog` (`id`, `name`) VALUES (NULL, '救助故事');
INSERT INTO `pohome`.`catelog` (`id`, `name`) VALUES (NULL, '领养故事');
INSERT INTO `pohome`.`catelog` (`id`, `name`) VALUES (NULL, '志愿者服务');
INSERT INTO `pohome`.`catelog` (`id`, `name`) VALUES (NULL, '知识库');
INSERT INTO `pohome`.`catelog` (`id`, `name`) VALUES (NULL, '曹菡艾教授专栏');
INSERT INTO `pohome`.`catelog` (`id`, `name`) VALUES (NULL, '捐助信息公布');
INSERT INTO `pohome`.`catelog` (`id`, `name`) VALUES (NULL, '转载');
INSERT INTO `pohome`.`catelog` (`id`, `name`) VALUES (NULL, '大事记');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pohome`.`tag`
-- -----------------------------------------------------
START TRANSACTION;
USE `pohome`;
INSERT INTO `pohome`.`tag` (`id`, `name`) VALUES (NULL, '良乡基地');
INSERT INTO `pohome`.`tag` (`id`, `name`) VALUES (NULL, '模拟家庭');
INSERT INTO `pohome`.`tag` (`id`, `name`) VALUES (NULL, '小天使基金');
INSERT INTO `pohome`.`tag` (`id`, `name`) VALUES (NULL, '瀛家军');
INSERT INTO `pohome`.`tag` (`id`, `name`) VALUES (NULL, '行为训练');

COMMIT;

